export const questionAnswer = [
	"How do Eclipses occur? \n Eclipses are the scientific phenomena that occurs when any celestial body comes in shadow of another celestial body which can cause the blocking of light for temporary amount of time. There are mainly two types of eclipses that occur. They are:Solar eclipse and Lunar eclipse.",

	"Why do only some people on Earth see an eclipse at a given time? \n The person needs to be within or near the eclipse path to see the eclipse and if he/she is out of it,the eclipse is not observed. Lunar eclipses are visible from everywhere but in case of the solar eclipse, the moon casts the umbra and penumbra shadow over the Earth. Umbra is the shadow that gets smaller as it reaches the Earth and people in umbra will see a total eclipse while penumbra is the shadow that gets bigger as it reaches the Earth and people in penumbra will  only see a partial eclipse.",

	"What causes the Sun, Moon, and Earth to align?\nThe main reason for the Sun,Moon and Earth to align is the inclination of the Moon that is tilted about 5.1 degrees with it's ecliptic plane,inclination of Earth's orbit around the Sun and the Earth's axis is tilted at an angle of about 23.5 degrees with respect to it's ecliptic plane and due to nodes(intersection of the Moon's orbit and the ecliptic plane) and the different phases of the moon that cause the eclipses to occur accordingly.",

	"How often do eclipses occur?\nPartial lunar eclipses are pretty common and at least two partial lunar eclipses occur every year but the total lunar eclipses are rare.In case of solar eclipses, they occur every 18 months on earth.According to NASA, On averagethe same spot on Earth only gets to see a solar eclipse for a few minutes about every 375 years.After about every 18 years, similar eclipses are occurred as studied in the Saros cycle, which is approximately 18 years, 11 days and 8 hours cycles",
	"How do scientists know when and where eclipses will occur?\nScientists use the scientific table called Ephemerides that gives the positions of celestial objects at a specific time and now in advancement with technology, different apps are also available for monitoring the positions of the celestial bodies and navigating them accordingly.Eclipse season also gives information about the eclipses to occur.They use different mathematical models and their computational power to predict about the eclipses.",
	"What is the difference between a lunar and solar eclipse? \nIn solar eclipse, moon comes in between the Sun and the Earth and casts a  shadow over the Earth.It can further be divided into Total Solar Eclipse,Partial Solar Eclipse and AnnularSolar Eclipse. Similarly, in lunar eclipse, earth comes in between the Sun and the Earth which causes the Earth's shadow to fall on the moon. It can further be divided into Total Lunar Eclipse and Partial Lunar Eclipse.Lunar eclipses occur and remain for some hours and are safe to watch while solar eclipses occur only for few minutes and should not be looked at directly.",
	" What is an eclipse season and why do they occur approximately every six months (or twice a year)? \nEclipse seasons occur approximately every six months when the Sun is near one of the nodes.They occur due to the axial parallelism of the orbital plane of the Moon which is tilted about 5 degrees to the Earth's orbital plane. Each eclipse season lasts for about 35 days and solar and lunar eclipse can occur only this short period of time.About every six months, Earth comes to a sweet spot in its orbit where a perfect—or almost perfect—three-way alignment of the Earth, Moon, and Sun can occur. Each sweet spot lasts for about 34.5 days: an eclipse season.If there is a New Moon near the middle of an eclipse season, it will form a straight line with the Earth and the Sun. The result will be a total solar eclipse, or an annular solar eclipse, if the Moon is too far from Earth to cover the Sun completely. In a similar way, a Full Moon near the middle of an eclipse season will produce a total lunar eclipse.",
];
